name: Build new release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
        driver-opts: network=${{ job.services.redis.network }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: false
        builder: ${{ steps.buildx.outputs.name }}
        build-args: |
          RUST_TOOLCHAIN=nightly-2021-11-09
          BUILD_BASE_VERSION=alpine3.14
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: |
          ghcr.io/digicatapult/substrate-docker-build-base:${{ github.sha }}
          ghcr.io/digicatapult/substrate-docker-build-base:latest
          ghcr.io/digicatapult/substrate-docker-build-base:nightly-2021-11-09-alpine3.14
        labels: |
          org.opencontainers.image.title=substrate-docker-build-base
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ needs.get-version.outputs.version }}
          org.opencontainers.image.created=${{ needs.get-version.outputs.build_date }}
    - name: Publish image
      run: docker push --all-tags ghcr.io/digicatapult/substrate-docker-build-base
